const DEFAULT_CURRENCY = 'CHF';
const DEFAULT_MIN_DECIMALS = 0;
const DEFAULT_MAX_DECIMALS = 2;
const DEFAULT_LOCALE = 'en-EN';

export {
  DEFAULT_CURRENCY,
  DEFAULT_MIN_DECIMALS,
  DEFAULT_MAX_DECIMALS,
  DEFAULT_LOCALE,
};
